export const REMINDER_REPOSITORY = Symbol('REMINDER_REPOSITORY');
export const PUSH_SUBSCRIPTION_REPOSITORY = Symbol(
  'PUSH_SUBSCRIPTION_REPOSITORY',
);
export const PUSH_SENDER = Symbol('PUSH_SENDER');
